DS4SD/deepsearch-toolkit

docs/api-reference.md, mkdocs.yml, poetry.lock, pyproject.toml
=> Docs - Simplify API refs

docs/gallery/index.md
Signed-off-by: Lokesh Mishra <exomishra@gmail.com>
=> Fixed example link

docs/favicon.svg, mkdocs.yml
Signed-off-by: Lokesh Mishra <exomishra@gmail.com>
=> Changed logo/favicon for consistency with DeepSearch

deepsearch/documents/core/input_process.py
Signed-off-by: Lokesh Mishra <exomishra@gmail.com>
=> Fixed archive names for single pdf uploads

deepsearch/documents/cli/main.py, deepsearch/documents/core/create_report.py, deepsearch/documents/core/main.py, poetry.lock, pyproject.toml
Signed-off-by: Lokesh Mishra <mis@zurich.ibm.com>
=> fixes issue with '.' paths

examples/README.md
Signed-off-by: Lokesh Mishra <mis@zurich.ibm.com>
=> Corrected numbering in readme

docs/guide/apis.md
Signed-off-by: cau-git <60343111+cau-git@users.noreply.github.com>
=> Fix typo in documentation

deepsearch/cps/cli/cli_options.py, deepsearch/cps/client/components/documents.py, deepsearch/cps/data_indices/utils.py, deepsearch/documents/cli/main.py, deepsearch/documents/core/convert.py, deepsearch/documents/core/create_report.py, deepsearch/documents/core/input_process.py, deepsearch/documents/core/main.py, deepsearch/documents/core/utils.py, docs/guide/convert_doc.md, examples/notebooks/Convert_Documents.ipynb
Several changes:
- use CCS api to acquire document conversion report
- added CLI function to generate report after document conversion
- CLI is currently verbose: gives interactive information (result directory) and suggestions (to generate report) 
- updated documentation
=> Improve reports

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/pypi.yml
Signed-off-by: Panos Vagenas <panagiotis.vagenas@gmail.com>
=> ci(#38): propagate poetry version constraint

deepsearch/cps/client/api.py
Signed-off-by: agiova <giovannini.andrea@outlook.com>
=> fixing replacement of auth key in deepsearchconfig, closes issue #36

MAINTAINERS.md, deepsearch/cps/client/api.py
Signed-off-by: Panos Vagenas <35837085+vagenas@users.noreply.github.com>
=> feat: add token refresh

docs/css/custom.css, docs/gallery/index.md, examples/README.md, poetry.lock, pyproject.toml
- Point user to examples repo
- Add example cards in the docs
The cards render as follow
=> Examples v2

mkdocs.yml
Signed-off-by: Michele Dolfi <97102151+dolfim-ibm@users.noreply.github.com>
=> chore: update tracking

docs/gallery/index.md
Depends on https://github.com/DS4SD/deepsearch-examples/pull/10
=> Add chemistry example to gallery

deepsearch/cps/client/components/data_indices.py, deepsearch/cps/data_indices/utils.py, deepsearch/documents/core/common_routines.py, docs/guide/data_indices.md
Signed-off-by: Panos Vagenas <35837085+vagenas@users.noreply.github.com>
=> fix: fix document upload

deepsearch/cps/cli/projects.py, deepsearch/cps/client/components/projects.py, docs/guide/projects.md
Signed-off-by: Panos Vagenas <35837085+vagenas@users.noreply.github.com>
=> feat: add assigning of users to projects

deepsearch/documents/core/utils.py
Signed-off-by: Christoph Auer <CAU@zurich.ibm.com>
=> feat: Allow supported image file formats in conversion

deepsearch/documents/core/models.py
Signed-off-by: Christoph Auer <CAU@zurich.ibm.com>
=> Add key_infix_format spec for S3 coordinates

deepsearch/chemistry/models.py, deepsearch/chemistry/queries/__init__.py, deepsearch/chemistry/queries/molecules.py, deepsearch/chemistry/queries/queries.py
Introduces new query methods for the PatCID data:
- Deprecates the existing chemistry functions. All existing functionality is covered by the new ones.
- Introduces querying with SMARTS as well.
- Uses the new (to be released) orchestrator task for querying the knowledge database.
=> feat!: Chemistry Queries for PatCID2

poetry.lock, pyproject.toml
Changed urrlib3 version to a wider range to improve compatibility with other projects
=> fix: change urrlib3 dependency version
